### ISSUE TITLE
Taro's presentation

### ISSUE THREAD

**Issue by nickyito** [M-0923/wad202-final-project-nick#57]

**Comment by hitohata** [comment]
## Environment

* Documentation
 - [x] [API Document](https://github.com/M-0923/wad202-final-project-nick?tab=readme-ov-file#api-document)
 - [x] [GitHub Actions](https://github.com/M-0923/wad202-final-project-nick/actions)
 - [x] Issues & PR
   - [x] [Issue](https://github.com/M-0923/wad202-final-project-nick/issues/32) 
   - [x] [PR](https://github.com/M-0923/wad202-final-project-nick/pull/55)

## Approach
 - [x] [Re-model the provided classes](https://github.com/M-0923/wad202-final-project-nick/tree/main/frontend/js/helpers)
 - [x] Using [Flux **like** strategy](https://www.google.com/search?q=flux+js&tbm=isch&ved=2ahUKEwi8xZbI5cWDAxV0wskDHUBAB6gQ2-cCegQIABAA&oq=flux+&gs_lcp=CgNpbWcQARgAMgQIIxAnMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEULAEWLAEYIQOaABwAHgAgAHfAYgB6AKSAQUwLjEuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=5biXZfy-BfSEp84PwICdwAo&bih=959&biw=1920#imgrc=GAPZJNVjvNipnM)
   - [x] Created Store
   - [x] Created Renderer to update HTML
   
## Appendix
 - [x] Close this issue
